name: Pylint y Despliegue CI/CD

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:  
      - '**.py'

jobs:
  # 1. Fase de Linting corregida
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint fastapi uvicorn sqlalchemy pydantic

    - name: Analysing the code with pylint
      run: |
        PYTHONPATH=. pylint $(git ls-files '*.py') --disable=C,R,W,I,E0401,E0402 || true

  # 2. Empaquetado en Docker Hub
  build-and-push:
    needs: linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.REC_DHUB_USER }}
        password: ${{ secrets.REC_DHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.REC_DHUB_USER }}/apirexamen:latest

  # 3. Despliegue en AWS
  deploy-to-aws:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.REC_EC2_IP }}
        username: ${{ secrets.REC_EC2_USER }}
        key: ${{ secrets.REC_EC2_KEY }}
        script: |
          mkdir -p ~/examen
          cd ~/examen
          cat << 'EOF' > docker-compose.yml
          services:
            api:
              image: ${{ secrets.REC_DHUB_USER }}/apirexamen:latest
              ports:
                - "80:8000"
              restart: always
          EOF
          sudo docker compose pull
          sudo docker compose up -d